version: '3'

services:

  # Foxtaur Main
  foxtaur-main:
    image: foxtaur-main:latest
    container_name: foxtaur-main
    restart: always

    ports:
        - 127.0.0.1:5035:80
        - 0.0.0.0:10000:10000

    volumes:
      - foxtaur_logs:/opt/foxtaur/logs
      - foxtaur_mapfiles:/opt/foxtaur/mapfiles

    networks:
      - foxtaur-infrastructure_foxtaur-net

volumes:

  # Logs
  foxtaur_logs:

  # Mapfiles storage
  foxtaur_mapfiles:

networks:
  foxtaur-infrastructure_foxtaur-net:
    driver: bridge
    external: true


